#Notatki

In [ ]:
#Deklaracja wektora w pythonie
v = [3, 2]
v

[3, 2]

In [ ]:
#Deklaracja wektora przy użyciu NumPy
import numpy as np
v = np.array([3, 2])
v

array([3, 2])

In [ ]:
#Wektor trójwymiarowy
import numpy as np
v = np.array([[4, 1, 2]])
v

array([[4, 1, 2]])

In [ ]:
#Dodawanie wektorów
import numpy as np

v = np.array([3, 2])
w = np.array([2, -1])

v + w

array([5, 1])

In [ ]:
#Skalowanie wektorów
import numpy as np

v = np.array([3, 1])

w = 2 * v

w

array([6, 2])

In [ ]:
import numpy as np

v = np.array([3, 1])

w = 0.5 * v

w

array([1.5, 0.5])

In [ ]:
#Mnożenie macierzy przez wektor
import numpy as np

baza = np.array(
    [[3, 0],
     [0, 2]]
    )

v = np.array([1, 1])

nowy_v = baza.dot(v)

nowy_v

array([3, 2])

In [ ]:
import numpy as np

i_daszek = np.array([2, 0])
j_daszek = np.array([0, 3])

baza = np.array([i_daszek, j_daszek]).transpose()

v = np.array([1, 1])

nowy_v = baza.dot(v)

nowy_v

array([2, 3])

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

i_daszek = np.array([1, 0])
j_daszek = np.array([0, 1])

#przekształcanie
i_daszek = i_daszek * 2
j_daszek = j_daszek * 3

v = np.array([2, 1])

baza = np.array([i_daszek, j_daszek]).transpose()

nowy_v = baza.dot(v)
nowy_v

array([4, 3])

In [ ]:
import numpy as np

i_daszek = np.array([2, 3])
j_daszek = np.array([2, -1])

baza = np.array([i_daszek, j_daszek]).transpose()

v = np.array([2, 1])

nowy_v = baza.dot(v)

nowy_v

array([6, 5])

In [ ]:
#Łączenie dwóch przekształceń
import numpy as np

i_daszek1 = np.array([0, 1])
j_daszek1 = np.array([-1, 0])
przeksztalcenie1 = np.array([i_daszek1, j_daszek1]).transpose()

i_daszek2 = np.array([1, 0])
j_daszek2 = np.array([1, 1])
przeksztalcenie2 = np.array([i_daszek2, j_daszek2]).transpose()

polaczone = przeksztalcenie2 @ przeksztalcenie1

print('POŁĄCZONA MACIERZ:\n {}'.format(polaczone))

v = np.array([1, 2])
print(polaczone.dot(v))

POŁĄCZONA MACIERZ:
 [[ 1 -1]
 [ 1  0]]
[-1  1]


In [ ]:
#Łączenie dwóch przekształceń(w odwrotnej kolejności)
import numpy as np

i_daszek1 = np.array([0, 1])
j_daszek1 = np.array([-1, 0])
przeksztalcenie1 = np.array([i_daszek1, j_daszek1]).transpose()

i_daszek2 = np.array([1, 0])
j_daszek2 = np.array([1, 1])
przeksztalcenie2 = np.array([i_daszek2, j_daszek2]).transpose()

polaczone = przeksztalcenie1 @ przeksztalcenie2

print('POŁĄCZONA MACIERZ:\n {}'.format(polaczone))

v = np.array([1, 2])
print(polaczone.dot(v))

POŁĄCZONA MACIERZ:
 [[ 0 -1]
 [ 1  1]]
[-2  3]


In [ ]:
import numpy as np

i_daszek = np.array([3, 0])
j_daszek = np.array([0, 2])

baza = np.array([i_daszek, j_daszek]).transpose()

wyznacznik = np.linalg.det(baza)

print(wyznacznik)

6.0


In [ ]:
import numpy as np

i_daszek = np.array([1, 0])
j_daszek = np.array([1, 1])

baza = np.array([i_daszek, j_daszek]).transpose()

wyznacznik = np.linalg.det(baza)

print(wyznacznik)

1.0


In [ ]:
import numpy as np

i_daszek = np.array([-2, 1])
j_daszek = np.array([1, 2])

baza = np.array([i_daszek, j_daszek]).transpose()

wyznacznik = np.linalg.det(baza)

print(wyznacznik)

-5.000000000000001


In [ ]:
from numpy import array
from numpy.linalg import det

i_daszek = array([3, 1.5])
j_daszek = array([2, 1])

baza = array([i_daszek, j_daszek]).transpose()

wyznacznik = det(baza)

print(wyznacznik)

0.0


In [ ]:
#Badanie macierzy odwrotnej i jednostkowej
from sympy import *

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

odwrotna = A.inv()
jednostkowa = odwrotna * A

jednostkowa

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [ ]:
import numpy as np
from numpy.linalg import inv

A = np.array([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

B = np.array([
    44,
    56,
    72
])

X = inv(A).dot(B)
print(X)

[ 2. 34. -8.]


In [ ]:
from sympy import *

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

B = Matrix([
    44,
    56,
    72
])

X = A.inv() * B

X

Matrix([
[ 2],
[34],
[-8]])

In [3]:
#Rozkład własny macierzy
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([
    [1, 2],
    [4, 5]
])

wart_wlasne, wekt_wlasne = eig(A) #Rozkład macierzy A na czynniki

print('WARTOSCI WLASNE')
print(wart_wlasne)
print('WEKTORY WLASNE')
print(wekt_wlasne)

WARTOSCI WLASNE
[-0.46410162  6.46410162]
WEKTORY WLASNE
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


In [5]:
#Rozkład własny macierzy
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([
    [1, 2],
    [4, 5]
])

wart_wlasne, wekt_wlasne = eig(A) #Rozkład macierzy A na czynniki

print('WARTOSCI WLASNE')
print(wart_wlasne)
print('WEKTORY WLASNE')
print(wekt_wlasne)

print('\nODTWORZONA MACIERZ')
Q = wekt_wlasne
R = inv(Q)

L = diag(wart_wlasne)
B = Q @ L @ R #wymnażanie(Rekonstrukcja do pierwotnej macierzy A)

print(B)

WARTOSCI WLASNE
[-0.46410162  6.46410162]
WEKTORY WLASNE
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]

ODTWORZONA MACIERZ
[[1. 2.]
 [4. 5.]]


#Ćwiczenia

In [7]:
#Ćwiczenie 1
import numpy as np

i_daszek = np.array([2, 0])
j_daszek = np.array([0, 1.5])

baza = np.array([i_daszek, j_daszek]).transpose()

vector = np.array([1, 2])

nowy_vector = baza.dot(vector)
nowy_vector

array([2., 3.])

In [10]:
#Ćwiczenie 2
import numpy as np

i_daszek = np.array([-2, 1])
j_daszek = np.array([1, -2])

baza = np.array([i_daszek, j_daszek]).transpose()

vector = np.array([1, 2])

nowy_vector = baza.dot(vector)

print(nowy_vector)

[ 0 -3]


In [14]:
#Ćwiczenie 3
import numpy as np
from numpy.linalg import det

i_daszek = np.array([1, 0])
j_daszek = np.array([2, 2])

baza = np.array([i_daszek, j_daszek]).transpose()

wyznacznik = det(baza)

#Wyznacznik jest to wartość o którą pomnożył się obszar zajęty przez wektory
#Pierwotnie wektory i oraz j zajmowały obszar o wyznaczniku 1(potocznie mówiąc jedną kratkę)
#Gdy wartość wektora j zmieniła się na [2, 2] to wartość wyznacznika się podwoiła
#Obecnie wynosi 4 połowy kratki(gdyż doszło do ścięcia) co ostatecznie daje wartość 4*1/2 = 2
wyznacznik

2.0

In [17]:
#Ćwiczenie 5
import numpy as np
from numpy.linalg import inv

A = np.array([
    [3, 1, 0],
    [2, 4, 1],
    [3, 1, 8]
])

B = np.array([
    54,
    12,
    6
])

rozwiazanie = inv(A).dot(B)

rozwiazanie

array([19.8, -5.4, -6. ])